-- CreateTable
CREATE TABLE `Clients` (
    `CODIGO` INTEGER NOT NULL AUTO_INCREMENT,
    `DESCRICAO` VARCHAR(191) NOT NULL,
    `RG` VARCHAR(191) NOT NULL,
    `CEP` VARCHAR(191) NOT NULL,
    `CIDADE` VARCHAR(191) NOT NULL,
    `ESTADO` VARCHAR(191) NOT NULL,
    `PAIS` VARCHAR(191) NOT NULL,
    `TELEFONE` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
