-- CreateTable
CREATE TABLE `products` (
    `CODIGO` INTEGER NOT NULL DEFAULT 0,
    `DESCRICAO` VARCHAR(191) NOT NULL,
    `PRECO` FLOAT NOT NULL DEFAULT 0.000000,
    `APLICACAO` VARCHAR(191) NOT NULL DEFAULT '',
    `SKU` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
